VerbiageVoyage/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('verbiages/', views.VerbiageList.as_view(), name='verbiages_index'),
    path('verbiages/<int:verbiage_id>/', views.verbiages_detail, name="detail"),
    path('verbiages/create/', views.VerbiageCreate.as_view(), name='verbiages_create'),
    path('verbiages/<int:pk>/update/', views.VerbiageUpdate.as_view(), name='verbiages_update'),
    path('verbiages/<int:pk>/delete/', views.VerbiageDelete.as_view(), name='verbiages_delete'),
    path('verbiages/<int:verbiage_id>/add_etymology/', views.add_etymology, name="add_etymology"),
    path('verbiages/<int:verbiage_id>/assoc_fact/<int:fact_id>/', views.assoc_fact, name="assoc_fact"),
    path('verbiages/<int:verbaige_id>/unassoc_fact/<int:fact_id>/', views.unassoc_fact, name="unassoc_fact"),
    path('facts/', views.FactList.as_view(), name='facts_index'),
    path('facts/<int:pk>/', views.FactDetail.as_view(), name='facts_detail'),
    path('facts/create/', views.FactCreate.as_view(), name='facts_create'),
    path('facts/<int:pk>/update/', views.FactUpdate.as_view(), name='facts_update'),
    path('facts/<int:pk>/delete/', views.FactDelete.as_view(), name='facts_delete')
]

main_app/models.py
from django.db import models
from django.urls import reverse


class Fact(models.Model):
    fact = models.TextField(max_length=500)

    def __str__(self):
        return self.fact

    def get_absolute_url(self):
        return reverse('facts_detail', kwargs={'pk': self.id})


class Verbiage(models.Model):
    word = models.CharField(max_length=50)
    language = models.CharField(max_length=50)
    definition = models.TextField(max_length=250)
    facts = models.ManyToManyField(Fact)

    def __str__(self):
        return f"{self.word} ({self.language}): {self.definition}"

    def get_absolute_url(self):
        return reverse('detail', kwargs={'verbiage_id': self.id})

class Etymology(models.Model):
    year = models.IntegerField()
    example = models.TextField(max_length=250)
    verbiage = models.ForeignKey(Verbiage, on_delete=models.CASCADE)

    def __str__(self):
        return f"Example sentence: {self.example} (appeared on {self.year})."

    class Meta:
        ordering = ['-year']

main_app/forms.py
from django.forms import ModelForm
from .models import Etymology


class EtymolodyForm(ModelForm):
    class Meta:
        model = Etymology
        fields = ["year", "example"]

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Verbiage, Fact
from .forms import EtymolodyForm


class VerbiageList(ListView):
    model = Verbiage
    template_name = 'verbiages/index.html'


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def verbiages_detail(request, verbiage_id):
    verbiage = Verbiage.objects.get(id=verbiage_id)
    facts_verbiage_doesnt_have = Fact.objects.exclude(id__in=verbiage.facts.all().values_list('id'))
    etymology_form = EtymolodyForm()
    return render(request, 'verbiages/detail.html', { "verbiage": verbiage,
                                                      "etymology_form": etymology_form,
                                                      "facts": facts_verbiage_doesnt_have})


class VerbiageCreate(CreateView):
    model = Verbiage
    fields = ["word", "language", "definition"]


class VerbiageUpdate(UpdateView):
  model = Verbiage
  fields = ["word", "language", "definition"]


class VerbiageDelete(DeleteView):
  model = Verbiage
  success_url = '/verbiages/'


def add_etymology(request, verbiage_id):
    form = EtymolodyForm(request.POST)
    if form.is_valid():
        new_etymology = form.save(commit=False)
        new_etymology.verbiage_id = verbiage_id
        new_etymology.save()
    return redirect('detail', verbiage_id=verbiage_id)


def assoc_fact(request, verbiage_id, fact_id):
    Verbiage.objects.get(id=verbiage_id).facts.add(fact_id)
    return redirect('detail', verbiage_id=verbiage_id)


def unassoc_fact(request, verbiage_id, fact_id):
    Verbiage.objects.get(id=verbiage_id).facts.remove(fact_id)
    return redirect('detail', verbiage_id=verbiage_id)


class FactList(ListView):
    model = Fact


class FactUpdate(UpdateView):
    model = Fact
    fields = '__all__'


class FactDelete(DeleteView):
    model = Fact
    success_url = "/facts/"


class FactCreate(CreateView):
    model = Fact
    fields = ["fact"]


class FactDetail(DetailView):
    model = Fact

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Verbiage Voyage</h1>
<hr>
<p>The objective here is to venture off the beaten path of our everyday lexicon to better experience the mundane.</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <title>Verbiage Voyage</title>
</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;VerbiageVoyage</a></li>
                </ul>
                <ul class="right">
                    <li><a href={% url "about" %}>About</a></li>
                    <li><a href={% url "verbiages_create" %}>Add a Verbiage</a></li>
                    <li><a href={% url "verbiages_index" %}>View All My Verbiages</a></li>
                    <li><a href={% url "facts_create" %}>Add Fun Facts</a></li>
                    <li><a href={% url "facts_index" %}>View All Fun Facts</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer">
        <div class="right">All Rights Reserved, &copy; 2019 Verbiage Voyage &nbsp;</div>
    </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>Welcome to Verbiage Voyage!</h1>
    <hr>
    <p>A goldmine of words in different languages that express rare/unusual combination of thoughts, feelings, or actions.</p>
{% endblock %}

main_app/templates/main_app/fact_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Fact</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.fact }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'facts_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/fact_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Fact Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ fact.fact }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'facts_update' fact.id %}">Edit</a>
        <a href="{% url 'facts_delete' fact.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/fact_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.fact}}</span></h1>
  {% else %}
    <h1>Add Fact</h1>
  {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/fact_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Fact List</h1>

{% for fact in fact_list %}
  <a href="{% url 'facts_detail' fact.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ fact.fact }}</span>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/verbiage_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

    <h1>Delete Word</h1>
    <h4>Are you sure you want to delete <span class="teal-text">{{ verbiage.word }}</span></h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes - Delete!" class="btn">
        <a href="{% url 'detail' verbiage.id %}">Cancel</a>
    </form>

{% endblock %}

main_app/templates/main_app/verbiage_form.html
{% extends 'base.html' %}
{% block content %}
    {% if verbiage %}
        <h1>Edit <span class="teal-text">{{ verbiage.word }}</span></h1>
    {% else %}
        <h1>Add Verbiage</h1>
    {% endif %}
    <form action="" method="post">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
    </table>
      <hr>
      <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/verbiages/detail.html
{% extends 'base.html' %}
{% block content %}

    <h1>Verbiage Details</h1>

    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ verbiage.word }} ({{ verbiage.language }})</span>
                    <p>Definition: {{ verbiage.definition }}</p>
                </div>
                <div class="card-action">
                    <a href="{% url 'verbiages_update' verbiage.id %}">Edit</a>
                    <a href="{% url 'verbiages_delete' verbiage.id %}">Delete</a>
                </div>
            </div>
        </div>
        <div class="col s6">
            <form action="{% url 'add_etymology' verbiage.id %}" method="post">
                {% csrf_token %} {{ etymology_form.as_p }}
                <input type="submit" class="btn" value="Add Etymology">
            </form>
                <table class="striped">
                    <thead>
                        <tr>
                            <th>Year</th>
                            <th>Example</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for etymology in verbiage.etymology_set.all %}
                            <tr>
                                <td>{{ etymology.year }}</td>
                                <td>{{ etymology.example }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
        </div>
    </div>

    <hr>
    <div class="row">
        <div class="col s6">
            <h3>{{ verbiage.word }}'s Facts</h3>
            {% if verbiage.facts.count %}
                {% for fact in verbiage.facts.all %}
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">
                                <span>{{ fact.fact }}</span>
                            </span>
                        </div>
                    <div class="card-action">
                        <form action="{% url 'unassoc_fact' verbiage.id fact.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn">Remove</button>
                        </form>
                    </div>
                    </div>
                {% endfor %}
                {% else %}
                <h5>No Facts</h5>
            {% endif %}
        </div>
    <div class="col s6">
        <h3>Available Facts</h3>
        {% if facts.count %}
            {% for fact in facts.all %}
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">
                            <span>{{ fact.fact }}</span>
                        </span>
                    </div>
                <div class="card-action">
                    <form action="{% url 'assoc_fact' verbiage.id fact.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn" type="submit">Add</button>
                    </form>
                </div>
                </div>
            {% endfor %}
            {% else %}
            <h5>{{ verbiage.word }} already has all the available facts.</h5>
        {% endif %}
    </div>
    </div>

    <script>
  // create a datepicker
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // initialize the meal select
  var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>

{% endblock %}

main_app/templates/verbiages/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Verbiage List</h1>

{% for verbiage in verbiage_list %}
  <div class="card">
      <div class="card-content">
          <a href="{% url "detail" verbiage.id %}">
            <span class="card-title">{{ verbiage.word }} ({{ verbiage.language }})</span></a>
          <p>Definition: {{ verbiage.definition }}</p>
      </div>
  </div>
{% endfor %}

{% endblock %}